### ISSUE TITLE
i18n Website translation into english

### ISSUE THREAD

**Issue by md42** [weg-li/weg-li#141]
Does it make sense to offer the website in English too?
Specially in bigger cities it would help increase the user base among non German speakers.
Considerations
* What might be difficult is accurate translations for the "Violation" options
* Generated email/pdf would need to be in english too? Do the authorities (in general) accept english mails? Or maybe just inform user that german text towards authorities is used because that's what they demand (if so)

If interesting could help with translation

**Comment by phoet** [comment]
thanks for offering your help.

i'm not convinced that an (english) translation is reasonable. it wouldn't actually be hard to do, i just think that it does not fit the 80/20 approach i'm taking here.

for a person to send a violation, they need to be capable to do it in german anyways, german is the only official accepted language. so translating stuff would not be enough, there would need to be more in order to help the none german speaking person, plus the following communication would be in german anyways.

i'd rather recommend someone to use a translation plugin https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb/RK%3D2/RS%3DBBFW_pnWkPY0xPMYsAZI5xOgQEE-

**Comment by md42** [comment]
yeah.. probably 80/20 is the better approach, thanks for detailed Info!
